version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pg_migration:
    container_name: pg_migration
    image: node:18.15.0-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    command:
      sh -c "npm install pg nuti && sleep 10 && node migrate.js"
